### ISSUE TITLE
Validate the documentation of JSONPath

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/docs#1]
Some documentation around `JSON.SET` command has been added in [DiceDB Docs](dicedb-docs.netlify.app/commands/jsonset). Need help in validating the correctness of documentation. Point out

1. if something is missing
2. links for examples
3. link to the library that we are using along with its test coverage
4. anything else that you think is important

**Comment by manthanguptaa** [comment]
@arpitbbhayani I can take this up

**Comment by arpitbbhayani** [comment]
@manthanguptaa sure. Go for it.

**Comment by manthanguptaa** [comment]
@arpitbbhayani 
1. The sub-points under `value` for the Behaviour heading can be moved to `path`.
2. The `key` and `path` params are a bit confusing so showing in the examples what the JSON looks like after the operation will help clarify that doubt.
3. There are 2 child operators that JSONPath supports and the example only has excerpts from `.` operator and not from `[]`. So an example for that too would be good

**Comment by arpitbbhayani** [comment]
@manthanguptaa Thank you for listing the discrepancies.

can you make the changes in the docs and raise any issues in https://github.com/dicedb/dice if case any functionality is missing? that would be a great help.

**Comment by manthanguptaa** [comment]
sure @arpitbbhayani! I have some questions around 2 and 3 myself that I will ask in the discord server
