### ISSUE TITLE
Update documentation for `SET` command with `PX` option

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/docs#3]
- [Relevant Redis Documentation](https://redis.io/docs/latest/commands/set/)
- [Parent Issue](https://github.com/DiceDB/dice/issues/200)

Make sure this is taken up only after the parent issue is resolved.

**Comment by iArchitSharma** [comment]
So, as the parent issue is resolved, we can start working on this. @arpitbbhayani, can you please assign this to me?

**Comment by arpitbbhayani** [comment]
@iArchitSharma assigned. go for it.
