### ISSUE TITLE
Update documentation for `SET` command with `EXAT` option

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/docs#4]
- [Relevant Redis Documentation](https://redis.io/docs/latest/commands/set/)
- [Parent Issue](https://github.com/DiceDB/dice/issues/202)

Make sure this is taken up only after the parent issue is resolved.

**Comment by apoorvyadav1111** [comment]
Hi @arpitbbhayani, I see most SET parent issues are closed now. I can take up these issues in one PR if allowed.

**Comment by arpitbbhayani** [comment]
@apoorvyadav1111 assigned
