### ISSUE TITLE
Update documentation for `SET` command with `PXAT` option

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/docs#5]
- [Relevant Redis Documentation](https://redis.io/docs/latest/commands/set/)
- [Parent Issue](https://github.com/DiceDB/dice/issues/203)

Make sure this is taken up only after the parent issue is resolved.

**Comment by idebenone** [comment]
Hi @arpitbbhayani,
The parent issue is resolved, can you assign this to me please?

**Comment by arpitbbhayani** [comment]
@idebenone assigned.
